import {
  MedicalCycleActionEnum,
  MODULE_CODE,
  PatientsActionEnum,
  SysBulletinActionEnum,
  TaskActionEnum,
} from '../enum';

export const LIST_CODE_PERMISSION_FOR_SUPER_ADMIN = [
  // ORGANIZATIONS
  `SYSTEM::${MODULE_CODE.ORGANIZATIONS}::VIEW`,
  `SYSTEM::${MODULE_CODE.ORGANIZATIONS}::VIEW_DOCUMENT`,
  `SYSTEM::${MODULE_CODE.ORGANIZATIONS}::CREATE`,
  `SYSTEM::${MODULE_CODE.ORGANIZATIONS}::EDIT`,
  `SYSTEM::${MODULE_CODE.ORGANIZATIONS}::EXPORT`,
  // REGISTRATIONS
  `SYSTEM::${MODULE_CODE.REGISTRATIONS}::VIEW`,
  `SYSTEM::${MODULE_CODE.REGISTRATIONS}::EDIT`,
  `SYSTEM::${MODULE_CODE.REGISTRATIONS}::EXPORT`,
  // ORGANIZATION_USERS
  `SYSTEM::${MODULE_CODE.ORGANIZATION_USERS}::VIEW`,
  `SYSTEM::${MODULE_CODE.ORGANIZATION_USERS}::CREATE`,
  `SYSTEM::${MODULE_CODE.ORGANIZATION_USERS}::EDIT`,
  `SYSTEM::${MODULE_CODE.ORGANIZATION_USERS}::DELETE`,
  `SYSTEM::${MODULE_CODE.ORGANIZATION_USERS}::IMPORT`,
  `SYSTEM::${MODULE_CODE.ORGANIZATION_USERS}::EXPORT`,
  // CONFIGUARATION_ADMIN_STAFF
  `SYSTEM::${MODULE_CODE.CONFIGUARATION_ADMIN_STAFF}::VIEW`,
  `SYSTEM::${MODULE_CODE.CONFIGUARATION_ADMIN_STAFF}::CREATE`,
  `SYSTEM::${MODULE_CODE.CONFIGUARATION_ADMIN_STAFF}::EDIT`,
  `SYSTEM::${MODULE_CODE.CONFIGUARATION_ADMIN_STAFF}::DELETE`,
  `SYSTEM::${MODULE_CODE.CONFIGUARATION_ADMIN_STAFF}::IMPORT`,
  `SYSTEM::${MODULE_CODE.CONFIGUARATION_ADMIN_STAFF}::EXPORT`,
  // CONFIGUARATION_ROLE_PERMISSION
  `SYSTEM::${MODULE_CODE.CONFIGUARATION_ROLE_PERMISSION}::VIEW`,
  `SYSTEM::${MODULE_CODE.CONFIGUARATION_ROLE_PERMISSION}::CREATE`,
  `SYSTEM::${MODULE_CODE.CONFIGUARATION_ROLE_PERMISSION}::EDIT`,
  `SYSTEM::${MODULE_CODE.CONFIGUARATION_ROLE_PERMISSION}::DELETE`,
  // SUBSCRIPTIONS
  `SYSTEM::${MODULE_CODE.SUBSCRIPTIONS}::VIEW`,
  // SUBSCRIPTION_PLAN
  `SYSTEM::${MODULE_CODE.SUBSCRIPTION_PLAN}::VIEW`,
  `SYSTEM::${MODULE_CODE.SUBSCRIPTION_PLAN}::CREATE`,
  `SYSTEM::${MODULE_CODE.SUBSCRIPTION_PLAN}::EDIT`,
  `SYSTEM::${MODULE_CODE.SUBSCRIPTION_PLAN}::DELETE`,
  // ACTIVITY_LOG_ADMIN
  `SYSTEM::${MODULE_CODE.ACTIVITY_LOG_ADMIN}::VIEW`,
  // BULLETINS
  `SYSTEM::${MODULE_CODE.BULLETINS}::${SysBulletinActionEnum.B_A_TAB_VIEW}`,
  `SYSTEM::${MODULE_CODE.BULLETINS}::${SysBulletinActionEnum.B_A_TAB_CREATE}`,
  `SYSTEM::${MODULE_CODE.BULLETINS}::${SysBulletinActionEnum.B_A_TAB_EDIT}`,
  `SYSTEM::${MODULE_CODE.BULLETINS}::${SysBulletinActionEnum.B_A_TAB_DELETE}`,
  `SYSTEM::${MODULE_CODE.BULLETINS}::${SysBulletinActionEnum.B_N_TAB_VIEW}`,
  `SYSTEM::${MODULE_CODE.BULLETINS}::${SysBulletinActionEnum.B_N_TAB_CREATE}`,
  `SYSTEM::${MODULE_CODE.BULLETINS}::${SysBulletinActionEnum.B_N_TAB_EDIT}`,
  `SYSTEM::${MODULE_CODE.BULLETINS}::${SysBulletinActionEnum.B_N_TAB_DELETE}`,
  // DASHBOARD_ADMIN
  `SYSTEM::${MODULE_CODE.DASHBOARD_ADMIN}::VIEW`,
  // FEEDBACK_ADMIN
  `SYSTEM::${MODULE_CODE.FEEDBACK_ADMIN}::VIEW`,

  // MEDICAL_CYCLE_ADMIN
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_L_VIEW_LIST}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_L_EXPORT}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_L_ADD_PATIENT_NOTE}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_L_CLOSE_CYCLE}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_O_TAB_VIEW_OVERVIEW}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_O_TAB_UPDATE_BSA_REPORT}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_O_TAB_UPDATE_INITIAL_CONSULT}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_O_TAB_UPDATE_PATIENT_INFORMATION}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_CP_TAB_VIEW_CYCLE_PROGRESS}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_CP_TAB_UPDATE_BSA_REPORT}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_CP_TAB_UPDATE_TEST_RESULT}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_CP_TAB_ADD_TREATMENT_COMPONENT}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_CP_TAB_UPDATE_TREATMENT_COMPONENT}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_CP_TAB_ADD_PATIENT_NOTE}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_CP_TAB_RUN_CALCULATION_LOGIC}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_CP_TAB_CLOSE_CYCLE}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_S_TAB_VIEW_SYMPTOM}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_S_TAB_UPDATE_SYMPTOM}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_MT_TAB_VIEW_LIST_MEDICAL_TEST}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_MT_TAB_VIEW_DETAIL_MEDICAL_TEST}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_MT_TAB_UPDATE_INITIAL_CONSULT}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_MT_TAB_UPDATE_PATIENT_INFORMATION}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_MT_TAB_UPDATE_TEST_RESULT}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_MT_TAB_EXPORT_MEDICAL_TEST}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_T_TAB_VIEW_TREATMENT}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_T_TAB_VIEW_DETAIL_TREATMENT_COMPONENT}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_T_TAB_UPDATE_TREATMENT_COMPONENT}`,

  // PATIENTS_ADMIN
  `SYSTEM::${MODULE_CODE.PATIENTS_ADMIN}::${PatientsActionEnum.P_L_VIEW_LIST}`,
  `SYSTEM::${MODULE_CODE.PATIENTS_ADMIN}::${PatientsActionEnum.P_L_CREATE}`,
  `SYSTEM::${MODULE_CODE.PATIENTS_ADMIN}::${PatientsActionEnum.P_L_EXPORT}`,
  `SYSTEM::${MODULE_CODE.PATIENTS_ADMIN}::${PatientsActionEnum.P_MD_TAB_VIEW_MAIN_DETAIL}`,
  `SYSTEM::${MODULE_CODE.PATIENTS_ADMIN}::${PatientsActionEnum.P_MD_TAB_UPDATE_PATIENT_INFORMATION}`,
  `SYSTEM::${MODULE_CODE.PATIENTS_ADMIN}::${PatientsActionEnum.P_IC_TAB_VIEW_INITIAL_CONSULT}`,
  `SYSTEM::${MODULE_CODE.PATIENTS_ADMIN}::${PatientsActionEnum.P_IC_TAB_UPDATE_INITIAL_CONSULT}`,
  `SYSTEM::${MODULE_CODE.PATIENTS_ADMIN}::${PatientsActionEnum.P_BR_TAB_VIEW_BSA_REPORT}`,
  `SYSTEM::${MODULE_CODE.PATIENTS_ADMIN}::${PatientsActionEnum.P_BR_TAB_UPDATE_BSA_REPORT}`,
  `SYSTEM::${MODULE_CODE.PATIENTS_ADMIN}::${PatientsActionEnum.P_MC_TAB_VIEW_OVERVIEW}`,
  `SYSTEM::${MODULE_CODE.PATIENTS_ADMIN}::${PatientsActionEnum.P_MC_TAB_CREATE_PATIENT_CYCLE}`,
  `SYSTEM::${MODULE_CODE.PATIENTS_ADMIN}::${PatientsActionEnum.P_S_TAB_VIEW_SYMPTOM}`,
  `SYSTEM::${MODULE_CODE.PATIENTS_ADMIN}::${PatientsActionEnum.P_MT_TAB_VIEW_LIST_MEDICAL_TEST}`,
  `SYSTEM::${MODULE_CODE.PATIENTS_ADMIN}::${PatientsActionEnum.P_MT_TAB_VIEW_DETAIL_MEDICAL_TEST}`,
  `SYSTEM::${MODULE_CODE.PATIENTS_ADMIN}::${PatientsActionEnum.P_PN_TAB_VIEW_PATIENT_NOTE}`,
  `SYSTEM::${MODULE_CODE.PATIENTS_ADMIN}::${PatientsActionEnum.P_PN_TAB_ADD_PATIENT_NOTE}`,

  // HEALTH_APPRAISAL_FORM
  `SYSTEM::${MODULE_CODE.HEALTH_APPRAISAL_FORM}::VIEW`,

  // DISEASES
  `SYSTEM::${MODULE_CODE.DISEASES}::VIEW`,
  `SYSTEM::${MODULE_CODE.DISEASES}::CREATE`,
  `SYSTEM::${MODULE_CODE.DISEASES}::EDIT`,
  `SYSTEM::${MODULE_CODE.DISEASES}::DELETE`,
  `SYSTEM::${MODULE_CODE.DISEASES}::IMPORT`,
  `SYSTEM::${MODULE_CODE.DISEASES}::EXPORT`,

  // INITIAL_CONSULT_ALGORITHM,
  `SYSTEM::${MODULE_CODE.INITIAL_CONSULT_ALGORITHM}::VIEW`,

  // SHA_LOGIC
  `SYSTEM::${MODULE_CODE.SHA_LOGIC}::VIEW`,
  `SYSTEM::${MODULE_CODE.SHA_LOGIC}::CREATE`,
  `SYSTEM::${MODULE_CODE.SHA_LOGIC}::EDIT`,
  `SYSTEM::${MODULE_CODE.SHA_LOGIC}::DELETE`,
  `SYSTEM::${MODULE_CODE.SHA_LOGIC}::EXPORT`,

  // MECHANISM
  `SYSTEM::${MODULE_CODE.MECHANISM}::VIEW`,
  `SYSTEM::${MODULE_CODE.MECHANISM}::CREATE`,
  `SYSTEM::${MODULE_CODE.MECHANISM}::EDIT`,
  `SYSTEM::${MODULE_CODE.MECHANISM}::DELETE`,
  `SYSTEM::${MODULE_CODE.MECHANISM}::EXPORT`,

  // SYMPTOM
  `SYSTEM::${MODULE_CODE.SYMPTOM}::VIEW`,
  `SYSTEM::${MODULE_CODE.SYMPTOM}::EXPORT`,

  // BLENDS
  `SYSTEM::${MODULE_CODE.BLENDS}::VIEW`,
  `SYSTEM::${MODULE_CODE.BLENDS}::CREATE`,
  `SYSTEM::${MODULE_CODE.BLENDS}::EDIT`,
  `SYSTEM::${MODULE_CODE.BLENDS}::DELETE`,
  `SYSTEM::${MODULE_CODE.BLENDS}::IMPORT`,
  `SYSTEM::${MODULE_CODE.BLENDS}::EXPORT`,

  // MEDICAL_TEST
  `SYSTEM::${MODULE_CODE.MEDICAL_TEST}::VIEW`,
  `SYSTEM::${MODULE_CODE.MEDICAL_TEST}::EDIT`,
  `SYSTEM::${MODULE_CODE.MEDICAL_TEST}::EXPORT`,

  // MEDICINES
  `SYSTEM::${MODULE_CODE.MEDICINES}::VIEW`,

  // TASK
  `SYSTEM::${MODULE_CODE.TASK_ADMIN}::${TaskActionEnum.OVERVIEW_TAB_VIEW}`,

  `SYSTEM::${MODULE_CODE.TASK_ADMIN}::${TaskActionEnum.TASK_LIST_TAB_VIEW}`,
  `SYSTEM::${MODULE_CODE.TASK_ADMIN}::${TaskActionEnum.TASK_LIST_TAB_ADD}`,
  `SYSTEM::${MODULE_CODE.TASK_ADMIN}::${TaskActionEnum.TASK_LIST_TAB_UPDATE}`,
  `SYSTEM::${MODULE_CODE.TASK_ADMIN}::${TaskActionEnum.TASK_LIST_TAB_DELETE}`,

  `SYSTEM::${MODULE_CODE.TASK_ADMIN}::${TaskActionEnum.CATEGORY_TAB_VIEW}`,
  `SYSTEM::${MODULE_CODE.TASK_ADMIN}::${TaskActionEnum.CATEGORY_TAB_ADD}`,
  `SYSTEM::${MODULE_CODE.TASK_ADMIN}::${TaskActionEnum.CATEGORY_TAB_UPDATE}`,
  `SYSTEM::${MODULE_CODE.TASK_ADMIN}::${TaskActionEnum.CATEGORY_TAB_DELETE}`,

  `SYSTEM::${MODULE_CODE.TASK_ADMIN}::${TaskActionEnum.TEMPLATE_TAB_VIEW}`,
  `SYSTEM::${MODULE_CODE.TASK_ADMIN}::${TaskActionEnum.TEMPLATE_TAB_UPDATE}`,
  `SYSTEM::${MODULE_CODE.TASK_ADMIN}::${TaskActionEnum.TEMPLATE_TAB_ADD}`,
  `SYSTEM::${MODULE_CODE.TASK_ADMIN}::${TaskActionEnum.TEMPLATE_TAB_DELETE}`,
];

export const LIST_CODE_PERMISSION_FOR_ADMIN = [
  // ORGANIZATIONS
  `SYSTEM::${MODULE_CODE.ORGANIZATIONS}::VIEW`,
  `SYSTEM::${MODULE_CODE.ORGANIZATIONS}::VIEW_DOCUMENT`,
  `SYSTEM::${MODULE_CODE.ORGANIZATIONS}::CREATE`,
  `SYSTEM::${MODULE_CODE.ORGANIZATIONS}::EDIT`,
  `SYSTEM::${MODULE_CODE.ORGANIZATIONS}::EXPORT`,
  // REGISTRATIONS
  `SYSTEM::${MODULE_CODE.REGISTRATIONS}::VIEW`,
  `SYSTEM::${MODULE_CODE.REGISTRATIONS}::EDIT`,
  `SYSTEM::${MODULE_CODE.REGISTRATIONS}::EXPORT`,
  // ORGANIZATION_USERS
  `SYSTEM::${MODULE_CODE.ORGANIZATION_USERS}::VIEW`,
  `SYSTEM::${MODULE_CODE.ORGANIZATION_USERS}::CREATE`,
  `SYSTEM::${MODULE_CODE.ORGANIZATION_USERS}::EDIT`,
  `SYSTEM::${MODULE_CODE.ORGANIZATION_USERS}::DELETE`,
  `SYSTEM::${MODULE_CODE.ORGANIZATION_USERS}::IMPORT`,
  `SYSTEM::${MODULE_CODE.ORGANIZATION_USERS}::EXPORT`,
  // CONFIGUARATION_ADMIN_STAFF
  `SYSTEM::${MODULE_CODE.CONFIGUARATION_ADMIN_STAFF}::VIEW`,
  `SYSTEM::${MODULE_CODE.CONFIGUARATION_ADMIN_STAFF}::CREATE`,
  `SYSTEM::${MODULE_CODE.CONFIGUARATION_ADMIN_STAFF}::EDIT`,
  `SYSTEM::${MODULE_CODE.CONFIGUARATION_ADMIN_STAFF}::DELETE`,
  `SYSTEM::${MODULE_CODE.CONFIGUARATION_ADMIN_STAFF}::IMPORT`,
  `SYSTEM::${MODULE_CODE.CONFIGUARATION_ADMIN_STAFF}::EXPORT`,
  // CONFIGUARATION_ROLE_PERMISSION
  `SYSTEM::${MODULE_CODE.CONFIGUARATION_ROLE_PERMISSION}::VIEW`,
  `SYSTEM::${MODULE_CODE.CONFIGUARATION_ROLE_PERMISSION}::CREATE`,
  `SYSTEM::${MODULE_CODE.CONFIGUARATION_ROLE_PERMISSION}::EDIT`,
  `SYSTEM::${MODULE_CODE.CONFIGUARATION_ROLE_PERMISSION}::DELETE`,
  // SUBSCRIPTIONS
  `SYSTEM::${MODULE_CODE.SUBSCRIPTIONS}::VIEW`,
  // SUBSCRIPTION_PLAN
  `SYSTEM::${MODULE_CODE.SUBSCRIPTION_PLAN}::VIEW`,
  `SYSTEM::${MODULE_CODE.SUBSCRIPTION_PLAN}::CREATE`,
  `SYSTEM::${MODULE_CODE.SUBSCRIPTION_PLAN}::EDIT`,
  `SYSTEM::${MODULE_CODE.SUBSCRIPTION_PLAN}::DELETE`,
  // ACTIVITY_LOG_ADMIN
  `SYSTEM::${MODULE_CODE.ACTIVITY_LOG_ADMIN}::VIEW`,
  // BULLETINS
  `SYSTEM::${MODULE_CODE.BULLETINS}::${SysBulletinActionEnum.B_A_TAB_VIEW}`,
  `SYSTEM::${MODULE_CODE.BULLETINS}::${SysBulletinActionEnum.B_A_TAB_CREATE}`,
  `SYSTEM::${MODULE_CODE.BULLETINS}::${SysBulletinActionEnum.B_A_TAB_EDIT}`,
  `SYSTEM::${MODULE_CODE.BULLETINS}::${SysBulletinActionEnum.B_A_TAB_DELETE}`,
  `SYSTEM::${MODULE_CODE.BULLETINS}::${SysBulletinActionEnum.B_N_TAB_VIEW}`,
  `SYSTEM::${MODULE_CODE.BULLETINS}::${SysBulletinActionEnum.B_N_TAB_CREATE}`,
  `SYSTEM::${MODULE_CODE.BULLETINS}::${SysBulletinActionEnum.B_N_TAB_EDIT}`,
  `SYSTEM::${MODULE_CODE.BULLETINS}::${SysBulletinActionEnum.B_N_TAB_DELETE}`,
  // DASHBOARD_ADMIN
  `SYSTEM::${MODULE_CODE.DASHBOARD_ADMIN}::VIEW`,
  // FEEDBACK_ADMIN
  `SYSTEM::${MODULE_CODE.FEEDBACK_ADMIN}::VIEW`,

  // MEDICAL_CYCLE_ADMIN
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_L_VIEW_LIST}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_L_EXPORT}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_L_ADD_PATIENT_NOTE}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_L_CLOSE_CYCLE}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_O_TAB_VIEW_OVERVIEW}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_O_TAB_UPDATE_BSA_REPORT}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_O_TAB_UPDATE_INITIAL_CONSULT}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_O_TAB_UPDATE_PATIENT_INFORMATION}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_CP_TAB_VIEW_CYCLE_PROGRESS}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_CP_TAB_UPDATE_BSA_REPORT}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_CP_TAB_UPDATE_TEST_RESULT}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_CP_TAB_ADD_TREATMENT_COMPONENT}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_CP_TAB_UPDATE_TREATMENT_COMPONENT}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_CP_TAB_ADD_PATIENT_NOTE}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_CP_TAB_RUN_CALCULATION_LOGIC}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_CP_TAB_CLOSE_CYCLE}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_S_TAB_VIEW_SYMPTOM}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_S_TAB_UPDATE_SYMPTOM}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_MT_TAB_VIEW_LIST_MEDICAL_TEST}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_MT_TAB_VIEW_DETAIL_MEDICAL_TEST}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_MT_TAB_UPDATE_INITIAL_CONSULT}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_MT_TAB_UPDATE_PATIENT_INFORMATION}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_MT_TAB_UPDATE_TEST_RESULT}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_MT_TAB_EXPORT_MEDICAL_TEST}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_T_TAB_VIEW_TREATMENT}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_T_TAB_VIEW_DETAIL_TREATMENT_COMPONENT}`,
  `SYSTEM::${MODULE_CODE.MEDICAL_CYCLE_ADMIN}::${MedicalCycleActionEnum.MC_T_TAB_UPDATE_TREATMENT_COMPONENT}`,

  // PATIENTS_ADMIN
  `SYSTEM::${MODULE_CODE.PATIENTS_ADMIN}::${PatientsActionEnum.P_L_VIEW_LIST}`,
  `SYSTEM::${MODULE_CODE.PATIENTS_ADMIN}::${PatientsActionEnum.P_L_CREATE}`,
  `SYSTEM::${MODULE_CODE.PATIENTS_ADMIN}::${PatientsActionEnum.P_L_EXPORT}`,
  `SYSTEM::${MODULE_CODE.PATIENTS_ADMIN}::${PatientsActionEnum.P_MD_TAB_VIEW_MAIN_DETAIL}`,
  `SYSTEM::${MODULE_CODE.PATIENTS_ADMIN}::${PatientsActionEnum.P_MD_TAB_UPDATE_PATIENT_INFORMATION}`,
  `SYSTEM::${MODULE_CODE.PATIENTS_ADMIN}::${PatientsActionEnum.P_IC_TAB_VIEW_INITIAL_CONSULT}`,
  `SYSTEM::${MODULE_CODE.PATIENTS_ADMIN}::${PatientsActionEnum.P_IC_TAB_UPDATE_INITIAL_CONSULT}`,
  `SYSTEM::${MODULE_CODE.PATIENTS_ADMIN}::${PatientsActionEnum.P_BR_TAB_VIEW_BSA_REPORT}`,
  `SYSTEM::${MODULE_CODE.PATIENTS_ADMIN}::${PatientsActionEnum.P_BR_TAB_UPDATE_BSA_REPORT}`,
  `SYSTEM::${MODULE_CODE.PATIENTS_ADMIN}::${PatientsActionEnum.P_MC_TAB_VIEW_OVERVIEW}`,
  `SYSTEM::${MODULE_CODE.PATIENTS_ADMIN}::${PatientsActionEnum.P_MC_TAB_CREATE_PATIENT_CYCLE}`,
  `SYSTEM::${MODULE_CODE.PATIENTS_ADMIN}::${PatientsActionEnum.P_S_TAB_VIEW_SYMPTOM}`,
  `SYSTEM::${MODULE_CODE.PATIENTS_ADMIN}::${PatientsActionEnum.P_MT_TAB_VIEW_LIST_MEDICAL_TEST}`,
  `SYSTEM::${MODULE_CODE.PATIENTS_ADMIN}::${PatientsActionEnum.P_MT_TAB_VIEW_DETAIL_MEDICAL_TEST}`,
  `SYSTEM::${MODULE_CODE.PATIENTS_ADMIN}::${PatientsActionEnum.P_PN_TAB_VIEW_PATIENT_NOTE}`,
  `SYSTEM::${MODULE_CODE.PATIENTS_ADMIN}::${PatientsActionEnum.P_PN_TAB_ADD_PATIENT_NOTE}`,

  // HEALTH_APPRAISAL_FORM
  `SYSTEM::${MODULE_CODE.HEALTH_APPRAISAL_FORM}::VIEW`,

  // DISEASES
  `SYSTEM::${MODULE_CODE.DISEASES}::VIEW`,
  `SYSTEM::${MODULE_CODE.DISEASES}::CREATE`,
  `SYSTEM::${MODULE_CODE.DISEASES}::EDIT`,
  `SYSTEM::${MODULE_CODE.DISEASES}::DELETE`,
  `SYSTEM::${MODULE_CODE.DISEASES}::IMPORT`,
  `SYSTEM::${MODULE_CODE.DISEASES}::EXPORT`,

  // INITIAL_CONSULT_ALGORITHM,
  `SYSTEM::${MODULE_CODE.INITIAL_CONSULT_ALGORITHM}::VIEW`,

  // SHA_LOGIC
  `SYSTEM::${MODULE_CODE.SHA_LOGIC}::VIEW`,
  `SYSTEM::${MODULE_CODE.SHA_LOGIC}::CREATE`,
  `SYSTEM::${MODULE_CODE.SHA_LOGIC}::EDIT`,
  `SYSTEM::${MODULE_CODE.SHA_LOGIC}::DELETE`,
  `SYSTEM::${MODULE_CODE.SHA_LOGIC}::EXPORT`,

  // MECHANISM
  `SYSTEM::${MODULE_CODE.MECHANISM}::VIEW`,
  `SYSTEM::${MODULE_CODE.MECHANISM}::CREATE`,
  `SYSTEM::${MODULE_CODE.MECHANISM}::EDIT`,
  `SYSTEM::${MODULE_CODE.MECHANISM}::DELETE`,
  `SYSTEM::${MODULE_CODE.MECHANISM}::EXPORT`,

  // SYMPTOM
  `SYSTEM::${MODULE_CODE.SYMPTOM}::VIEW`,
  `SYSTEM::${MODULE_CODE.SYMPTOM}::EXPORT`,

  // BLENDS
  `SYSTEM::${MODULE_CODE.BLENDS}::VIEW`,
  `SYSTEM::${MODULE_CODE.BLENDS}::CREATE`,
  `SYSTEM::${MODULE_CODE.BLENDS}::EDIT`,
  `SYSTEM::${MODULE_CODE.BLENDS}::DELETE`,
  `SYSTEM::${MODULE_CODE.BLENDS}::IMPORT`,
  `SYSTEM::${MODULE_CODE.BLENDS}::EXPORT`,

  // MEDICAL_TEST
  `SYSTEM::${MODULE_CODE.MEDICAL_TEST}::VIEW`,
  `SYSTEM::${MODULE_CODE.MEDICAL_TEST}::EDIT`,
  `SYSTEM::${MODULE_CODE.MEDICAL_TEST}::EXPORT`,

  // MEDICINES
  `SYSTEM::${MODULE_CODE.MEDICINES}::VIEW`,

  // TASK
  `SYSTEM::${MODULE_CODE.TASK_ADMIN}::${TaskActionEnum.OVERVIEW_TAB_VIEW}`,

  `SYSTEM::${MODULE_CODE.TASK_ADMIN}::${TaskActionEnum.TASK_LIST_TAB_VIEW}`,
  `SYSTEM::${MODULE_CODE.TASK_ADMIN}::${TaskActionEnum.TASK_LIST_TAB_ADD}`,
  `SYSTEM::${MODULE_CODE.TASK_ADMIN}::${TaskActionEnum.TASK_LIST_TAB_UPDATE}`,
  `SYSTEM::${MODULE_CODE.TASK_ADMIN}::${TaskActionEnum.TASK_LIST_TAB_DELETE}`,

  `SYSTEM::${MODULE_CODE.TASK_ADMIN}::${TaskActionEnum.CATEGORY_TAB_VIEW}`,
  `SYSTEM::${MODULE_CODE.TASK_ADMIN}::${TaskActionEnum.CATEGORY_TAB_ADD}`,
  `SYSTEM::${MODULE_CODE.TASK_ADMIN}::${TaskActionEnum.CATEGORY_TAB_UPDATE}`,
  `SYSTEM::${MODULE_CODE.TASK_ADMIN}::${TaskActionEnum.CATEGORY_TAB_DELETE}`,

  `SYSTEM::${MODULE_CODE.TASK_ADMIN}::${TaskActionEnum.TEMPLATE_TAB_VIEW}`,
  `SYSTEM::${MODULE_CODE.TASK_ADMIN}::${TaskActionEnum.TEMPLATE_TAB_UPDATE}`,
  `SYSTEM::${MODULE_CODE.TASK_ADMIN}::${TaskActionEnum.TEMPLATE_TAB_ADD}`,
  `SYSTEM::${MODULE_CODE.TASK_ADMIN}::${TaskActionEnum.TEMPLATE_TAB_DELETE}`,
];

export const LIST_CODE_PERMISSION_FOR_COMPANY_ADMIN = [
  // ORGANIZATION_PROFILE
  `ORGANIZATION::${MODULE_CODE.ORGANIZATION_PROFILE}::VIEW`,
  `ORGANIZATION::${MODULE_CODE.ORGANIZATION_PROFILE}::VIEW_DOCUMENT`,
  `ORGANIZATION::${MODULE_CODE.ORGANIZATION_PROFILE}::EDIT`,
  // ORGANIZATION_MEMBER
  `ORGANIZATION::${MODULE_CODE.ORGANIZATION_MEMBER}::VIEW`,
  `ORGANIZATION::${MODULE_CODE.ORGANIZATION_MEMBER}::CREATE`,
  `ORGANIZATION::${MODULE_CODE.ORGANIZATION_MEMBER}::EDIT`,
  `ORGANIZATION::${MODULE_CODE.ORGANIZATION_MEMBER}::DELETE`,
  `ORGANIZATION::${MODULE_CODE.ORGANIZATION_MEMBER}::IMPORT`,
  `ORGANIZATION::${MODULE_CODE.ORGANIZATION_MEMBER}::EXPORT`,

  // SUBSCRIPTION_DETAIL
  `ORGANIZATION::${MODULE_CODE.SUBSCRIPTION_DETAIL}::VIEW`,
  `ORGANIZATION::${MODULE_CODE.SUBSCRIPTION_DETAIL}::EDIT`,
  // ACTIVITY_LOG
  `ORGANIZATION::${MODULE_CODE.ACTIVITY_LOG}::VIEW`,
  // DASHBOARD
  `ORGANIZATION::${MODULE_CODE.DASHBOARD}::VIEW`,
  // FEEDBACK
  `ORGANIZATION::${MODULE_CODE.FEEDBACK}::CREATE`,

  // MEDICAL_CYCLE
  `ORGANIZATION::${MODULE_CODE.MEDICAL_CYCLE}::${MedicalCycleActionEnum.MC_L_VIEW_LIST}`,
  `ORGANIZATION::${MODULE_CODE.MEDICAL_CYCLE}::${MedicalCycleActionEnum.MC_L_EXPORT}`,
  `ORGANIZATION::${MODULE_CODE.MEDICAL_CYCLE}::${MedicalCycleActionEnum.MC_L_ADD_PATIENT_NOTE}`,
  `ORGANIZATION::${MODULE_CODE.MEDICAL_CYCLE}::${MedicalCycleActionEnum.MC_L_CLOSE_CYCLE}`,
  `ORGANIZATION::${MODULE_CODE.MEDICAL_CYCLE}::${MedicalCycleActionEnum.MC_O_TAB_VIEW_OVERVIEW}`,
  `ORGANIZATION::${MODULE_CODE.MEDICAL_CYCLE}::${MedicalCycleActionEnum.MC_O_TAB_UPDATE_BSA_REPORT}`,
  `ORGANIZATION::${MODULE_CODE.MEDICAL_CYCLE}::${MedicalCycleActionEnum.MC_O_TAB_UPDATE_INITIAL_CONSULT}`,
  `ORGANIZATION::${MODULE_CODE.MEDICAL_CYCLE}::${MedicalCycleActionEnum.MC_O_TAB_UPDATE_PATIENT_INFORMATION}`,
  `ORGANIZATION::${MODULE_CODE.MEDICAL_CYCLE}::${MedicalCycleActionEnum.MC_CP_TAB_VIEW_CYCLE_PROGRESS}`,
  `ORGANIZATION::${MODULE_CODE.MEDICAL_CYCLE}::${MedicalCycleActionEnum.MC_CP_TAB_UPDATE_BSA_REPORT}`,
  `ORGANIZATION::${MODULE_CODE.MEDICAL_CYCLE}::${MedicalCycleActionEnum.MC_CP_TAB_UPDATE_TEST_RESULT}`,
  `ORGANIZATION::${MODULE_CODE.MEDICAL_CYCLE}::${MedicalCycleActionEnum.MC_CP_TAB_ADD_TREATMENT_COMPONENT}`,
  `ORGANIZATION::${MODULE_CODE.MEDICAL_CYCLE}::${MedicalCycleActionEnum.MC_CP_TAB_UPDATE_TREATMENT_COMPONENT}`,
  `ORGANIZATION::${MODULE_CODE.MEDICAL_CYCLE}::${MedicalCycleActionEnum.MC_CP_TAB_ADD_PATIENT_NOTE}`,
  `ORGANIZATION::${MODULE_CODE.MEDICAL_CYCLE}::${MedicalCycleActionEnum.MC_CP_TAB_RUN_CALCULATION_LOGIC}`,
  `ORGANIZATION::${MODULE_CODE.MEDICAL_CYCLE}::${MedicalCycleActionEnum.MC_CP_TAB_CLOSE_CYCLE}`,
  `ORGANIZATION::${MODULE_CODE.MEDICAL_CYCLE}::${MedicalCycleActionEnum.MC_S_TAB_VIEW_SYMPTOM}`,
  `ORGANIZATION::${MODULE_CODE.MEDICAL_CYCLE}::${MedicalCycleActionEnum.MC_S_TAB_UPDATE_SYMPTOM}`,
  `ORGANIZATION::${MODULE_CODE.MEDICAL_CYCLE}::${MedicalCycleActionEnum.MC_MT_TAB_VIEW_LIST_MEDICAL_TEST}`,
  `ORGANIZATION::${MODULE_CODE.MEDICAL_CYCLE}::${MedicalCycleActionEnum.MC_MT_TAB_VIEW_DETAIL_MEDICAL_TEST}`,
  `ORGANIZATION::${MODULE_CODE.MEDICAL_CYCLE}::${MedicalCycleActionEnum.MC_MT_TAB_UPDATE_INITIAL_CONSULT}`,
  `ORGANIZATION::${MODULE_CODE.MEDICAL_CYCLE}::${MedicalCycleActionEnum.MC_MT_TAB_UPDATE_PATIENT_INFORMATION}`,
  `ORGANIZATION::${MODULE_CODE.MEDICAL_CYCLE}::${MedicalCycleActionEnum.MC_MT_TAB_UPDATE_TEST_RESULT}`,
  `ORGANIZATION::${MODULE_CODE.MEDICAL_CYCLE}::${MedicalCycleActionEnum.MC_MT_TAB_EXPORT_MEDICAL_TEST}`,
  `ORGANIZATION::${MODULE_CODE.MEDICAL_CYCLE}::${MedicalCycleActionEnum.MC_T_TAB_VIEW_TREATMENT}`,
  `ORGANIZATION::${MODULE_CODE.MEDICAL_CYCLE}::${MedicalCycleActionEnum.MC_T_TAB_VIEW_DETAIL_TREATMENT_COMPONENT}`,
  `ORGANIZATION::${MODULE_CODE.MEDICAL_CYCLE}::${MedicalCycleActionEnum.MC_T_TAB_UPDATE_TREATMENT_COMPONENT}`,

  // PATIENTS
  `ORGANIZATION::${MODULE_CODE.PATIENTS}::${PatientsActionEnum.P_L_VIEW_LIST}`,
  `ORGANIZATION::${MODULE_CODE.PATIENTS}::${PatientsActionEnum.P_L_CREATE}`,
  `ORGANIZATION::${MODULE_CODE.PATIENTS}::${PatientsActionEnum.P_L_EXPORT}`,
  `ORGANIZATION::${MODULE_CODE.PATIENTS}::${PatientsActionEnum.P_MD_TAB_VIEW_MAIN_DETAIL}`,
  `ORGANIZATION::${MODULE_CODE.PATIENTS}::${PatientsActionEnum.P_MD_TAB_UPDATE_PATIENT_INFORMATION}`,
  `ORGANIZATION::${MODULE_CODE.PATIENTS}::${PatientsActionEnum.P_IC_TAB_VIEW_INITIAL_CONSULT}`,
  `ORGANIZATION::${MODULE_CODE.PATIENTS}::${PatientsActionEnum.P_IC_TAB_UPDATE_INITIAL_CONSULT}`,
  `ORGANIZATION::${MODULE_CODE.PATIENTS}::${PatientsActionEnum.P_BR_TAB_VIEW_BSA_REPORT}`,
  `ORGANIZATION::${MODULE_CODE.PATIENTS}::${PatientsActionEnum.P_BR_TAB_UPDATE_BSA_REPORT}`,
  `ORGANIZATION::${MODULE_CODE.PATIENTS}::${PatientsActionEnum.P_MC_TAB_VIEW_OVERVIEW}`,
  `ORGANIZATION::${MODULE_CODE.PATIENTS}::${PatientsActionEnum.P_MC_TAB_CREATE_PATIENT_CYCLE}`,
  `ORGANIZATION::${MODULE_CODE.PATIENTS}::${PatientsActionEnum.P_S_TAB_VIEW_SYMPTOM}`,
  `ORGANIZATION::${MODULE_CODE.PATIENTS}::${PatientsActionEnum.P_MT_TAB_VIEW_LIST_MEDICAL_TEST}`,
  `ORGANIZATION::${MODULE_CODE.PATIENTS}::${PatientsActionEnum.P_MT_TAB_VIEW_DETAIL_MEDICAL_TEST}`,
  `ORGANIZATION::${MODULE_CODE.PATIENTS}::${PatientsActionEnum.P_PN_TAB_VIEW_PATIENT_NOTE}`,
  `ORGANIZATION::${MODULE_CODE.PATIENTS}::${PatientsActionEnum.P_PN_TAB_ADD_PATIENT_NOTE}`,

  // USER_REGISTRATION
  `ORGANIZATION::${MODULE_CODE.USER_REGISTRATION}::VIEW`,
  `ORGANIZATION::${MODULE_CODE.USER_REGISTRATION}::EDIT`,
  `ORGANIZATION::${MODULE_CODE.USER_REGISTRATION}::EXPORT`,

  // TASK
  `ORGANIZATION::${MODULE_CODE.TASK}::${TaskActionEnum.OVERVIEW_TAB_VIEW}`,

  `ORGANIZATION::${MODULE_CODE.TASK}::${TaskActionEnum.TASK_LIST_TAB_VIEW}`,
  `ORGANIZATION::${MODULE_CODE.TASK}::${TaskActionEnum.TASK_LIST_TAB_ADD}`,
  `ORGANIZATION::${MODULE_CODE.TASK}::${TaskActionEnum.TASK_LIST_TAB_UPDATE}`,
  `ORGANIZATION::${MODULE_CODE.TASK}::${TaskActionEnum.TASK_LIST_TAB_DELETE}`,

  `ORGANIZATION::${MODULE_CODE.TASK}::${TaskActionEnum.CATEGORY_TAB_VIEW}`,
  `ORGANIZATION::${MODULE_CODE.TASK}::${TaskActionEnum.CATEGORY_TAB_ADD}`,
  `ORGANIZATION::${MODULE_CODE.TASK}::${TaskActionEnum.CATEGORY_TAB_UPDATE}`,
  `ORGANIZATION::${MODULE_CODE.TASK}::${TaskActionEnum.CATEGORY_TAB_DELETE}`,

  `ORGANIZATION::${MODULE_CODE.TASK}::${TaskActionEnum.TEMPLATE_TAB_VIEW}`,
  `ORGANIZATION::${MODULE_CODE.TASK}::${TaskActionEnum.TEMPLATE_TAB_UPDATE}`,
  `ORGANIZATION::${MODULE_CODE.TASK}::${TaskActionEnum.TEMPLATE_TAB_ADD}`,
  `ORGANIZATION::${MODULE_CODE.TASK}::${TaskActionEnum.TEMPLATE_TAB_DELETE}`,
];
