import { IconSvgName } from './enum';
import { MODULE_CODE } from '../enum/module.enum';

export const MENUS = [
  {
    name: 'Homepage',
    code: MODULE_CODE.HOMEPAGE,
    description: 'Home Page',
    url: '',
    orderNum: 1,
    status: 1,
    menus: [
      {
        name: 'Dashboard',
        code: MODULE_CODE.DASHBOARD,
        description: 'Dashboard',
        url: '/dashboard',
        orderNum: 11,
        icon: IconSvgName.DASHBOARD,
        status: 1,
        menus: [],
      },
      {
        name: 'Dashboard',
        code: MODULE_CODE.DASHBOARD_ADMIN,
        description: 'Dashboard',
        url: '/admin/dashboard',
        orderNum: 11,
        icon: IconSvgName.DASHBOARD,
        status: 1,
        menus: [],
      },
    ],
  },

  {
    name: 'Organization Config',
    code: MODULE_CODE.ORGANIZATION_MANAGEMENT,
    description: 'Organization management',
    url: '',
    orderNum: 2,
    status: 1,
    menus: [
      {
        name: 'Organization Profile',
        code: MODULE_CODE.ORGANIZATION_PROFILE,
        description: 'Organization Profile',
        url: '/organization',
        icon: IconSvgName.ORGANIZATIONS,
        orderNum: 21,
        status: 1,
      },
      {
        name: 'User Registrations',
        code: MODULE_CODE.USER_REGISTRATION,
        description: 'User Registrations',
        url: '/user-registrations',
        icon: IconSvgName.USER_REGISTRATION,
        orderNum: 22,
        status: 1,
      },
      {
        name: 'Registrations',
        code: MODULE_CODE.REGISTRATIONS,
        description: 'Registrations',
        url: '/admin/registration',
        icon: IconSvgName.REGISTRATIONS,
        orderNum: 22,
        status: 1,
      },
      {
        name: 'Organizations',
        code: MODULE_CODE.ORGANIZATIONS,
        description: 'Organizations',
        url: '/admin/organization',
        icon: IconSvgName.ORGANIZATIONS,
        orderNum: 23,
        status: 1,
      },
      {
        name: 'Organization Members',
        code: MODULE_CODE.ORGANIZATION_MEMBER,
        description: 'Organization Members',
        url: '/member',
        icon: IconSvgName.ORGANIZATION_USERS,
        orderNum: 24,
        status: 1,
      },
      {
        name: 'Organization Users',
        code: MODULE_CODE.ORGANIZATION_USERS,
        description: 'Organization Users',
        url: '/admin/member',
        icon: IconSvgName.ORGANIZATION_USERS,
        orderNum: 24,
        status: 1,
      },
      {
        name: 'Subscription Detail',
        code: MODULE_CODE.SUBSCRIPTION_DETAIL,
        description: 'Organization Member',
        url: '/subscription/detail',
        icon: IconSvgName.SUBSCRIPTIONS,
        orderNum: 25,
        status: 1,
      },
    ],
  },
  {
    name: 'Medical Cycle',
    code: MODULE_CODE.PATIENT_MANAGEMENT,
    description: 'Medical Cycle',
    url: '',
    orderNum: 3,
    status: 1,
    menus: [
      {
        name: 'Medical Cycles',
        code: MODULE_CODE.MEDICAL_CYCLE,
        description: 'Medical Cycles',
        url: '/medical-cycle',
        icon: IconSvgName.MEDICAL_CYCLE,
        orderNum: 31,
        status: 1,
      },
      {
        name: 'Medical Cycles',
        code: MODULE_CODE.MEDICAL_CYCLE_ADMIN,
        description: 'Medical Cycles For Admin',
        url: '/admin/medical-cycle',
        icon: IconSvgName.MEDICAL_CYCLE,
        orderNum: 31,
        status: 1,
      },
      {
        name: 'Patients',
        code: MODULE_CODE.PATIENTS,
        description: 'Patients User',
        url: '/patients',
        icon: IconSvgName.PATIENTS,
        orderNum: 32,
        status: 1,
      },
      {
        name: 'Patients',
        code: MODULE_CODE.PATIENTS_ADMIN,
        description: 'Patients Admin',
        url: '/admin/patients',
        icon: IconSvgName.PATIENTS,
        orderNum: 32,
        status: 1,
      },
    ],
  },
  {
    name: 'CDME Framework',
    code: MODULE_CODE.CDME_FRAMEWORK,
    description: 'CDME Framework',
    url: '',
    orderNum: 4,
    status: 1,
    menus: [
      {
        name: 'Diseases',
        code: MODULE_CODE.DISEASES,
        description: 'Diseases Admin',
        url: '/admin/diseases',
        icon: IconSvgName.DISEASES,
        orderNum: 41,
        status: 1,
      },
      {
        name: 'Symptoms',
        code: MODULE_CODE.SYMPTOM,
        description: 'Symptom Admin',
        url: '/admin/symptom',
        icon: IconSvgName.SYMPTOM,
        orderNum: 42,
        status: 1,
      },
      {
        name: 'Blends',
        code: MODULE_CODE.BLENDS,
        description: 'Blends',
        url: '/admin/diseases',
        icon: IconSvgName.BLENDS,
        orderNum: 43,
        status: 1,
      },
      {
        name: 'Medical Tests',
        code: MODULE_CODE.MEDICAL_TEST,
        description: 'Medical Tests for Admin',
        url: '/admin/medical-test',
        icon: IconSvgName.MEDICAL_TEST,
        orderNum: 44,
        status: 1,
      },
      {
        name: 'Initial Consult Algorithm',
        code: MODULE_CODE.INITIAL_CONSULT_ALGORITHM,
        description: 'Initial Consult Algorithm Admin',
        url: '/admin/initial-consult-algorithm',
        icon: IconSvgName.INITIAL_CONSULT_ALGORITHM,
        orderNum: 45,
        status: 1,
      },
      {
        name: 'Health Appraisal Form',
        code: MODULE_CODE.HEALTH_APPRAISAL_FORM,
        description: 'Health Appraisal Form Admin',
        url: '/admin/health-appraisal-form',
        icon: IconSvgName.HEALTH_APPRAISAL_FORM,
        orderNum: 46,
        status: 1,
      },
      {
        name: 'Subjective Health Analysis',
        code: MODULE_CODE.SHA_LOGIC,
        description: 'Subjective Health Analysis Admin',
        url: '/admin/sha-logic',
        icon: IconSvgName.SHA_LOGIC,
        orderNum: 47,
        status: 1,
      },
      {
        name: 'Mechanisms',
        code: MODULE_CODE.MECHANISM,
        description: 'Mechanisms Admin',
        url: '/admin/mechanism',
        icon: IconSvgName.MECHANISM,
        orderNum: 48,
        status: 1,
      },
      {
        name: 'Medicines',
        code: MODULE_CODE.MEDICINES,
        description: 'Medicines Admin',
        url: '/admin/medicines',
        icon: IconSvgName.MEDICINES,
        orderNum: 49,
        status: 1,
      },
    ],
  },
  {
    name: 'System Config',
    code: MODULE_CODE.SYSTEM_CONFIGURATION_USER,
    description: 'System Config For Client Site',
    url: '',
    orderNum: 5,
    status: 1,
    menus: [
      {
        name: 'Activity Log',
        code: MODULE_CODE.ACTIVITY_LOG,
        description: 'Activity Log',
        url: '/activity-member',
        icon: IconSvgName.ACTIVITY_LOG,
        orderNum: 51,
        status: 1,
      },
    ],
  },
  {
    name: 'System Config',
    code: MODULE_CODE.SYSTEM_CONFIGURATION,
    description: 'System Configuration for Admin',
    url: '',
    orderNum: 6,
    status: 1,
    menus: [
      {
        name: 'Admin Staff',
        code: MODULE_CODE.CONFIGUARATION_ADMIN_STAFF,
        description: 'Admin Staff',
        url: '/admin/admin-staff',
        icon: IconSvgName.ADMIN_STAFF,
        orderNum: 61,
        status: 1,
      },
      {
        name: 'Roles & Permissions',
        code: MODULE_CODE.CONFIGUARATION_ROLE_PERMISSION,
        description: 'Roles & Permissions',
        url: '/admin/role-and-permission',
        icon: IconSvgName.ROLE_PERMISSION,
        orderNum: 62,
        status: 1,
      },
      {
        name: 'Bulletins',
        code: MODULE_CODE.BULLETINS,
        description: 'Bulletins',
        url: '/admin/bulletins',
        icon: IconSvgName.BULLETINS,
        orderNum: 63,
        status: 1,
      },
      {
        name: 'Activity Log',
        code: MODULE_CODE.ACTIVITY_LOG_ADMIN,
        description: 'Activity Log',
        url: '/admin/activity',
        icon: IconSvgName.ACTIVITY_LOG,
        orderNum: 64,
        status: 1,
      },
    ],
  },
  {
    name: 'Subscription Config',
    code: MODULE_CODE.SUBSCRIPTION_MANAGEMENT,
    description: 'Subscription Config',
    url: '',
    orderNum: 7,
    status: 1,
    menus: [
      {
        name: 'Subscriptions',
        code: MODULE_CODE.SUBSCRIPTIONS,
        description: 'Subscriptions',
        url: '/admin/subscription',
        icon: IconSvgName.SUBSCRIPTIONS,
        orderNum: 71,
        status: 1,
      },
      {
        name: 'Plans & Pricing',
        code: MODULE_CODE.SUBSCRIPTION_PLAN,
        description: 'Subscription Plan',
        url: '/admin/plan-and-pricing',
        icon: IconSvgName.SUBSCRIPTION_PLAN,
        orderNum: 72,
        status: 1,
      },
    ],
  },
  {
    name: 'Customer Support',
    code: MODULE_CODE.CUSTOMER_SUPPORT,
    description: 'Customer Support For User Site',
    url: '',
    orderNum: 8,
    status: 1,
    menus: [
      {
        name: 'Feedbacks',
        code: MODULE_CODE.FEEDBACK,
        description: 'Feedbacks',
        url: '/feedbacks',
        icon: IconSvgName.FEEDBACK,
        orderNum: 81,
        status: 1,
      },
    ],
  },
  {
    name: 'Customer Support',
    code: MODULE_CODE.CUSTOMER_SUPPORT,
    description: 'Customer Support For Admin Site',
    url: '',
    orderNum: 9,
    status: 1,
    menus: [
      {
        name: 'Feedbacks',
        code: MODULE_CODE.FEEDBACK_ADMIN,
        description: 'Feedbacks',
        url: '/admin/feedbacks',
        icon: IconSvgName.FEEDBACK,
        orderNum: 91,
        status: 1,
      },
    ],
  },
];
