export enum MessagePatternEnum {
  IDENTITY_AUTH_REGISTER = 'IDENTITY_AUTH_REGISTER',
  IDENTITY_AUTH_REGISTER_ORGANIZATION = 'IDENTITY_AUTH_REGISTER_ORGANIZATION',
  IDENTITY_AUTH_LOGIN = 'IDENTITY_AUTH_LOGIN',
  IDENTITY_AUTH_GET_ME = 'IDENTITY_AUTH_GET_ME',
  IDENTITY_USER_GET_PROFILE = 'IDENTITY_USER_GET_PROFILE',

  // Role patterns
  IDENTITY_RBAC_CREATE_ROLE = 'IDENTITY_RBAC_CREATE_ROLE',
  IDENTITY_RBAC_GET_ALL_ROLES = 'IDENTITY_RBAC_GET_ALL_ROLES',
  IDENTITY_RBAC_GET_ROLE = 'IDENTITY_RBAC_GET_ROLE',
  IDENTITY_RBAC_UPDATE_ROLE = 'IDENTITY_RBAC_UPDATE_ROLE',
  IDENTITY_RBAC_DELETE_ROLE = 'IDENTITY_RBAC_DELETE_ROLE',
  IDENTITY_RBAC_ASSIGN_PERMISSION = 'IDENTITY_RBAC_ASSIGN_PERMISSION',
  IDENTITY_RBAC_REMOVE_PERMISSION = 'IDENTITY_RBAC_REMOVE_PERMISSION',
  IDENTITY_RBAC_GET_ROLE_PERMISSIONS = 'IDENTITY_RBAC_GET_ROLE_PERMISSIONS',

  // Permission patterns
  IDENTITY_RBAC_CREATE_PERMISSION = 'IDENTITY_RBAC_CREATE_PERMISSION',
  IDENTITY_RBAC_GET_ALL_PERMISSIONS = 'IDENTITY_RBAC_GET_ALL_PERMISSIONS',
  IDENTITY_RBAC_GET_PERMISSION = 'IDENTITY_RBAC_GET_PERMISSION',
  IDENTITY_RBAC_UPDATE_PERMISSION = 'IDENTITY_RBAC_UPDATE_PERMISSION',
  IDENTITY_RBAC_DELETE_PERMISSION = 'IDENTITY_RBAC_DELETE_PERMISSION',

  // RBAC patterns
  IDENTITY_RBAC_ASSIGN_ROLE = 'IDENTITY_RBAC_ASSIGN_ROLE',
  IDENTITY_RBAC_REMOVE_ROLE = 'IDENTITY_RBAC_REMOVE_ROLE',
  IDENTITY_RBAC_GET_USER_ROLES = 'IDENTITY_RBAC_GET_USER_ROLES',
  IDENTITY_RBAC_GET_USER_PERMISSIONS = 'IDENTITY_RBAC_GET_USER_PERMISSIONS',
  IDENTITY_RBAC_CHECK_PERMISSION = 'IDENTITY_RBAC_CHECK_PERMISSION',
}
